export const products = [
    {
        id: 1,
        title: 'Mobile',
        brand: 'Redmi',
        name: 'Redmi 12C',
        price: 14999,
        color: 'Silver',
        details: 'RedmiRedmi 12 (Moonstone Silver, 6GB RAM, 128B Storage)',
        imageUrl: 'https://m.media-amazon.com/images/I/61SmnheBBRL._AC_UL320_.jpg',
    },
    {
        id: 2,
        title: 'Mobile',
        brand: 'Redmi',
        name: 'Redmi A2',
        price: 5299,
        color: 'Blue',
        details: 'Redmi A2 (Aqua Blue, 2GB RAM, 64GB Storage)',
        imageUrl: 'https://m.media-amazon.com/images/I/81bh6SxXQ+L._AC_UL320_.jpg',
    },
    {
        id: 3,
        title: 'Mobile',
        brand: 'Redmi',
        name: 'Redmi A2',
        price: 5299,
        color: 'Black',
        details: 'Redmi A2 (Classic Black, 2GB RAM, 64GB Storage)',
        imageUrl: 'https://m.media-amazon.com/images/I/810-BAwpF9L._AC_UL320_.jpg',
    },
    {
        id: 4,
        title: 'Mobile',
        brand: 'Redmi',
        name: 'Redmi 12 5G',
        price: 14999,
        color: 'Black',
        details: 'Redmi 12 5G Jade Black 8GB RAM 256GB ROM',
        imageUrl: 'https://m.media-amazon.com/images/I/71tCOhEigtL._AC_UL320_.jpg',
    },
    {
        id: 5,
        title: 'Mobile',
        brand: 'POCO',
        name: 'POCO M6 Pro 5G',
        price: 11999,
        color: 'Black',
        details: 'POCO M6 Pro 5G (Power Black, 128 GB) (4 GB RAM)',
        imageUrl: 'https://m.media-amazon.com/images/I/41OfNqG32nL._AC_UY218_.jpg',
    },
    {
        id: 6,
        title: 'Mobile',
        brand: 'Redmi',
        name: 'Redmi 12C',
        price: 9229,
        color: 'Blue',
        details: 'Redmi 12C (Royal Blue, 6GB RAM, 128GB Storage) | High Performance Mediatek Helio G85 | Big 17cm(6.71) HD+ Display with 5000mAh(typ) Battery',
        imageUrl: 'https://m.media-amazon.com/images/I/81itQPVn-GL._AC_UL320_.jpg',
    },
    {
        id: 7,
        title: 'Mobile',
        brand: 'Samsung',
        name: 'Samsung F04',
        price: 8999,
        color: 'Green',
        details: 'Samsung F04 Smart Phone (Opal Green, 4GB RAM 64GB Storage)',
        imageUrl: 'https://m.media-amazon.com/images/I/8110mANA0rL._AC_UY218_.jpg',
    },
    {
        id: 8,
        title: 'Mobile',
        brand: 'Motorola',
        name: 'Motorola E13',
        price: 8287,
        color: 'Green',
        details: 'Motorola E13 (Aurora Green, 8GB RAM, 128GB Storage) | Upto 1TB MicroSD Expandable | 6.5-inch IPS LCD Display with 60Hz Refresh Rate | UNISOC T606 Processor | Face Unlock | IP52 Water Repellent Design 3.9 out of 5 stars 116',
        imageUrl: 'https://m.media-amazon.com/images/I/61ne46L6QdL._AC_UY218_.jpg',
    },
    {
        id: 9,
        title: 'Mobile',
        brand: 'POCO',
        name: 'POCO C51',
        price: 78890,
        color: 'Blue',
        details: 'POCO C51 (Royal Blue)',
        imageUrl: 'https://m.media-amazon.com/images/I/51ZuW-0fiiL._AC_UY218_.jpg',
    },
    {
        id: 10,
        title: 'Mobile',
        brand: 'Motorola',
        name: 'Motorola G84',
        price: 22449,
        color: 'Magenta',
        details: 'Motorola G84 5G (Viva Magenta, 12GB RAM, 256GB Storage)',
        imageUrl: 'https://m.media-amazon.com/images/I/51HnWtX7klL._AC_UY218_.jpg',
    },
    {
        id: 11,
        title: 'Mobile',
        brand: 'Motorola',
        name: 'Motorola Edge 40 Neo',
        price: 29999,
        details: 'Motorola Edge 40 Neo (Soothing Sea, 256 GB) (12 GB RAM)',
        imageUrl: 'https://m.media-amazon.com/images/I/61bUETZj9AL._AC_UY218_.jpg',
    },
    {
        id: 12,
        title: 'Mobile',
        brand: 'Samsung',
        name: 'Samsung Galaxy S21 FE 5G',
        price: 33999,
        color: 'Green',
        details: 'Samsung Galaxy S21 FE 5G SMARPHONE (Olive Green, 8GB RAM 128GB Storage)',
        imageUrl: 'https://m.media-amazon.com/images/I/71nj3tkXZXL._AC_UL320_.jpg',
    },
    // Add more products as needed
];